#define GREETING_TPC "/GREETING"

#define AUTHORIZATION_REQUESTS_TPC "/AUTHORIZATION_REQUESTS"
#define AUTHORIZATION_REQUESTS_STATUS_TPC "/AUTHORIZATION_REQUESTS_STATUS"

#define DEVICE_SETTINGS_REQUEST_TPC "/DEVICE_SETTINGS_REQUESTS"
#define DEVICE_SETTINGS_APPLY_TPC "/DEVICE_SETTINGS_APPLY"